"""Official gas-well sources. Endpoints and filters were verified 2026-09-24."""

from ingest.status_map import compile_map

BROWSER_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
)

# States the manifest must list even when no source is usable.
ALL_AREAS = [
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA",
    "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
    "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT",
    "VA", "WA", "WV", "WI", "WY", "DC", "US-OCS",
]

PRIORITY = ["TX", "PA", "OH", "WV", "OK", "NM", "LA", "CO"]


def _src(**kwargs):
    mapping = kwargs.pop("mapping")
    kwargs["status_table"] = compile_map(mapping)
    kwargs.setdefault("user_agent", BROWSER_UA)
    kwargs.setdefault("page_size", 1000)
    kwargs.setdefault("enabled", True)
    return kwargs


SOURCES = [
    _src(
        state="TX",
        agency="Railroad Commission of Texas (RRC)",
        source_name="RRC Public GIS Viewer, Well Locations (layer 1)",
        source_url="https://gis.rrc.texas.gov/server/rest/services/rrc_public/RRC_Public_Viewer_Srvs/MapServer/1",
        kind="arcgis",
        page_size=1000,
        where="GIS_SYMBOL_DESCRIPTION IN ('Gas Well','Shut-In Gas','Plugged Gas Well','Oil/Gas Well','Plugged Oil / Gas')",
        out_fields="API,GIS_API5,GIS_WELL_NUMBER,GIS_SYMBOL_DESCRIPTION,GIS_LAT83,GIS_LONG83",
        api=["API"],
        name=["GIS_WELL_NUMBER"],
        operator=[],
        type_fields=["GIS_SYMBOL_DESCRIPTION"],
        status=["GIS_SYMBOL_DESCRIPTION"],
        date_fields=[],
        lat=["GIS_LAT83"],
        lon=["GIS_LONG83"],
        source_updated="UNKNOWN",
        coverage="partial status",
        note="RRC GIS has shut-in versus gas-well status only. No operator or dates in this layer.",
        mapping={
            "Active_or_unknown": ["Gas Well", "Oil/Gas Well"],
            "Inactive": ["Shut-In Gas"],
            "Plugged": ["Plugged Gas Well", "Plugged Oil / Gas"],
            "Other": ["Injection / Disposal from Gas", "Storage from Gas"],
        },
    ),
    _src(
        state="PA",
        agency="PA DEP (served by PASDA)",
        source_name="Oil Gas Locations Conventional Unconventional 2026_09 (layer 22)",
        source_url="https://mapservices.pasda.psu.edu/server/rest/services/pasda/DEP/MapServer/22",
        kind="arcgis",
        page_size=1000,
        where="WELL_TYPE IN ('GAS','COMB. OIL&GAS','COALBED METHANE')",
        out_fields="PERMIT_NUM,WELL_NAME,OPERATOR,WELL_TYPE,WELL_STATU,PERMIT_DAT,SPUD_DATE,DATE_PLUGG,LATITUDE,LONGITUDE",
        api=["PERMIT_NUM"],
        name=["WELL_NAME"],
        operator=["OPERATOR"],
        type_fields=["WELL_TYPE"],
        status=["WELL_STATU"],
        date_fields=["DATE_PLUGG", "SPUD_DATE", "PERMIT_DAT"],
        lat=["LATITUDE"],
        lon=["LONGITUDE"],
        source_updated="2026-09-02",
        coverage="live full status",
        resolve_layer_name="Oil Gas Locations",
        mapping={
            "Active": ["Active"],
            "Inactive": ["Regulatory Inactive Status"],
            "Plugged": ["Plugged OG Well", "DEP Plugged", "Plugged Unverified"],
            "Other": [
                "Abandoned",
                "DEP Abandoned List",
                "DEP Orphan List",
                "Proposed But Never Materialized",
                "Operator Reported Not Drilled",
                "Cannot Be Located",
                "Uncharted Mined Through",
                "Duplicate",
            ],
        },
    ),
    _src(
        state="OH",
        agency="Ohio DNR Division of Oil and Gas",
        source_name="Oilgas_Wells_public (layer 0)",
        source_url="https://gis.ohiodnr.gov/arcgis/rest/services/DOG_Services/Oilgas_Wells_public/MapServer/0",
        kind="arcgis",
        page_size=1000,
        where="MapSymbol_DESC IN ('Gas','Gas with oil show','Oil and gas','Plugged gas','Plugged gas with oil show','Plugged oil and gas','Coalbed methane')",
        out_fields="API_WELLNO,WELL_NM,CO_NAME,MapSymbol_DESC,WL_STATUS_DESC,Last_Inspection_Date,Last_Nonzero_Production_Year,WH_LAT,WH_LONG",
        api=["API_WELLNO"],
        name=["WELL_NM"],
        operator=["CO_NAME"],
        type_fields=["MapSymbol_DESC"],
        status=["WL_STATUS_DESC"],
        date_fields=["Last_Inspection_Date", "Last_Nonzero_Production_Year"],
        lat=["WH_LAT"],
        lon=["WH_LONG"],
        source_updated="2026-09-21",
        coverage="live full status",
        mapping={
            "Active": ["Producing"],
            "Inactive": ["Well Drilled"],
            "Plugged": ["Final Restoration", "Plugged and Abandoned"],
            "Other": [
                "Unknown status",
                "Field Inspected, Well Not Found",
                "Orphan Well - Ready",
                "Orphan Well - Pending",
                "Permit Expired",
                "Storage Well",
            ],
        },
    ),
    _src(
        state="WV",
        agency="WV DEP Office of Oil and Gas",
        source_name="All DEP Wells (layer 7)",
        source_url="https://tagis.dep.wv.gov/arcgis/rest/services/WVDEP_enterprise/oil_gas/MapServer/7",
        kind="arcgis",
        page_size=2000,
        where="welluse LIKE '%Gas%' AND welluse NOT LIKE '%Storage%'",
        out_fields="api,farmname,wellnumber,respparty,welluse,wellstatus,issuedate,compdate",
        api=["api"],
        name=["farmname", "wellnumber"],
        operator=["respparty"],
        type_fields=["welluse"],
        status=["wellstatus"],
        date_fields=["compdate", "issuedate"],
        lat=[],
        lon=[],
        source_updated="UNKNOWN",
        coverage="live full status",
        mapping={
            "Active": ["Active Well"],
            "Inactive": ["Shutin", "Future Use"],
            "Plugged": ["Plugged"],
            "Other": ["Abandoned Well", "Never Drilled", "Permit Issued"],
        },
    ),
    _src(
        state="OK",
        agency="Oklahoma Corporation Commission",
        source_name="RBDMS_WELLS (layer 2)",
        source_url="https://gis.occ.ok.gov/server/rest/services/Hosted/RBDMS_WELLS/FeatureServer/2",
        kind="arcgis",
        page_size=2000,
        where="welltype='GAS'",
        out_fields="api,well_name,well_num,operator,welltype,wellstatus",
        api=["api"],
        name=["well_name", "well_num"],
        operator=["operator"],
        type_fields=["welltype"],
        status=["wellstatus"],
        date_fields=[],
        lat=["sh_lat"],
        lon=["sh_lon"],
        source_updated="2026-09-24",
        coverage="live full status",
        mapping={
            "Active": ["AC"],
            "Inactive": ["TA", "SIFORDER", "SFFO", "SP"],
            "Plugged": ["PA", "PAFF", "PASF", "STFD"],
            "Other": ["OR", "NE", "TM", "EX"],
        },
    ),
    _src(
        state="NM",
        agency="NM EMNRD Oil Conservation Division",
        source_name="OCDView Wells_Public (layer 0)",
        source_url="https://gis.emnrd.nm.gov/arcgis/rest/services/OCDView/Wells_Public/FeatureServer/0",
        kind="arcgis",
        page_size=2000,
        where="type='Gas'",
        out_fields="id,name,ogrid_name,type,status,last_production_date,plug_date,spud_date,latitude,longitude",
        api=["id"],
        name=["name"],
        operator=["ogrid_name"],
        type_fields=["type"],
        status=["status"],
        date_fields=["last_production_date", "plug_date", "spud_date"],
        lat=["latitude"],
        lon=["longitude"],
        source_updated="2026-08-01",
        coverage="live full status",
        mapping={
            "Active": ["Active"],
            "Inactive": ["Temporary Abandonment", "TA (expired)"],
            "Plugged": ["Plugged (site released)", "Plugged (not released)", "Zone Plugged (permanent)", "Zone Plugged (temporary)"],
            "Other": ["Cancelled", "New", "Never Drilled", "Reclamation Fund Approved", "Dry Hole"],
        },
    ),
    _src(
        state="LA",
        agency="Louisiana Dept of Conservation and Energy (SONRIS)",
        source_name="DNRSvc OC wells (layer 0)",
        source_url="https://sonris-gis.dnr.la.gov/arcgis/rest/services/DNRSvc/OC/MapServer/0",
        kind="arcgis",
        page_size=1000,
        where="PRODUCT_TYPE_CODE IN ('20','25')",
        out_fields="API_NUM,WELL_NAME,ORG_OPER_NAME,PRODUCT_TYPE_CODE,WELL_STATUS_CODE,WELL_STATUS_DATE,SURFACE_LAT_DEC_DEG,SURFACE_LONG_DEC_DEG",
        api=["API_NUM"],
        name=["WELL_NAME"],
        operator=["ORG_OPER_NAME"],
        type_fields=["PRODUCT_TYPE_CODE"],
        status=["WELL_STATUS_CODE"],
        date_fields=["WELL_STATUS_DATE"],
        lat=["SURFACE_LAT_DEC_DEG"],
        lon=["SURFACE_LONG_DEC_DEG"],
        source_updated="2026-09-23",
        coverage="live full status",
        mapping={
            "Active": ["10"],
            "Inactive": ["33", "34", "36", "37", "18", "20"],
            "Plugged": ["30", "29", "35"],
            "Other": ["23", "28", "03"],
        },
    ),
    _src(
        state="CO",
        agency="Colorado Energy and Carbon Management Commission (ECMC)",
        source_name="WELLS_SHP.ZIP bulk shapefile",
        source_url="https://ecmc.state.co.us/documents/data/downloads/gis/WELLS_SHP.ZIP",
        kind="shapefile",
        where_field="Well_Class",
        where_values=["GW", "CBM"],
        api=["API_Label"],
        name=["Well_Name"],
        operator=["Operator"],
        type_fields=["Well_Class"],
        status=["Facil_Stat"],
        date_fields=["Stat_Date"],
        lat=["Latitude"],
        lon=["Longitude"],
        source_updated="2026-09-23",
        coverage="file snapshot",
        mapping={
            "Active": ["PR"],
            "Inactive": ["SI", "TA"],
            "Plugged": ["PA"],
            "Other": ["AL", "SO", "WO"],
        },
    ),
    _src(
        state="UT",
        agency="Utah DNR Division of Oil, Gas and Mining (via UGRC)",
        source_name="viewAGRC_WellData_Surf (layer 0)",
        source_url="https://services.arcgis.com/ZzrwjTRez6FJiOq4/arcgis/rest/services/viewAGRC_WellData_Surf/FeatureServer/0",
        kind="arcgis",
        page_size=2000,
        where="WellType='Gas Well'",
        out_fields="API,WellName,Operator,WellType,WellStatus,AbandonDate,OrigComplDate,Latitude,Longitude",
        api=["API"],
        name=["WellName"],
        operator=["Operator"],
        type_fields=["WellType"],
        status=["WellStatus"],
        date_fields=["AbandonDate", "OrigComplDate"],
        lat=["Latitude"],
        lon=["Longitude"],
        source_updated="2026-09-24",
        coverage="live full status",
        mapping={
            "Active": ["Producing", "Active"],
            "Inactive": ["Shut-in", "TA", "Inactive", "Temporarily-abandoned"],
            "Plugged": ["P&A", "Plugged & Abandoned"],
            "Other": ["LA", "Location Abandoned - APD rescinded", "Approved Permit", "Returned APD", "Returned APD (Unapproved)"],
        },
    ),
    _src(
        state="MI",
        agency="Michigan EGLE",
        source_name="GrmdOpenData oil and gas wells (layer 10)",
        source_url="https://gisagoegle.state.mi.us/arcgis/rest/services/EGLE/GrmdOpenData/MapServer/10",
        kind="arcgis",
        page_size=2000,
        where="WellType IN ('Natural Gas Well','Gas Condensate Well')",
        out_fields="api_num,WellName,CompanyName,WellType,WellStatus,PermitDate,PluggingDate",
        api=["api_num"],
        name=["WellName"],
        operator=["CompanyName"],
        type_fields=["WellType"],
        status=["WellStatus"],
        date_fields=["PermitDate", "PluggingDate"],
        lat=[],
        lon=[],
        source_updated="2026-08-25",
        coverage="live full status",
        mapping={
            "Active": ["Producing", "Active"],
            "Inactive": ["Temporarily Abandoned", "Shut_In"],
            "Plugged": ["Plugging Approved", "Plugging Completed", "Plugging Approved - Part 616", "Plugging Completed- Part 616"],
            "Other": ["Orphan", "Plugged Back", "Sump"],
        },
    ),
    _src(
        state="AR",
        agency="Arkansas Oil and Gas Commission (via Arkansas GIS Office)",
        source_name="FEATURESERVICES Utilities (layer 5)",
        source_url="https://gis.arkansas.gov/arcgis/rest/services/FEATURESERVICES/Utilities/FeatureServer/5",
        kind="arcgis",
        page_size=500,
        where="welltype='GAS'",
        out_fields="wellid,wellname,operatorname,welltype,wellstatus,wellstatusdescription,wellstatusdate,coordinates_latitude,coordinates_longitude",
        api=["wellid"],
        name=["wellname"],
        operator=["operatorname"],
        type_fields=["welltype"],
        status=["wellstatusdescription", "wellstatus"],
        date_fields=["wellstatusdate"],
        lat=["coordinates_latitude"],
        lon=["coordinates_longitude"],
        source_updated="UNKNOWN",
        coverage="live full status",
        mapping={
            "Active": ["Producing", "Domestic Well - Gas"],
            "Inactive": ["Temporarily Abandoned"],
            "Plugged": ["Plugged and Abandoned"],
            "Other": ["Expired Permit", "Abandoned/Orphaned", "Abandoned/Orphaned Well"],
        },
    ),
    _src(
        state="NY",
        agency="NY DEC Division of Mineral Resources (data.ny.gov)",
        source_name="Oil, Gas and Other Regulated Wells (Socrata szye-wmt3)",
        source_url="https://data.ny.gov/resource/szye-wmt3.json",
        kind="socrata",
        page_size=5000,
        where="well_type in('GD','GW')",
        api=["api_well_number"],
        name=["well_name"],
        operator=["company_name"],
        type_fields=["well_type"],
        status=["well_status"],
        date_fields=["status_date", "date_last_modified"],
        lat=["surface_latitude"],
        lon=["surface_longitude"],
        source_updated="2026-09-23",
        coverage="live full status",
        mapping={
            "Active": ["AC"],
            "Inactive": ["IN", "SI"],
            "Plugged": ["PA"],
            "Other": ["UM", "UL", "UN", "EX"],
        },
    ),
    _src(
        state="VA",
        agency="Virginia Energy, Division of Gas and Oil",
        source_name="DGO_wells Active Wells (layer 0) and Plugged (layer 5)",
        source_url="https://energy.virginia.gov/gis/rest/services/DGO/DGO_wells/FeatureServer/0",
        kind="arcgis",
        page_size=2000,
        where="TblOpDesc <> 'Oil'",
        out_fields="FiNo,FiFarm,CoName,TblOpDesc,TblPsDesc,FiStatDt",
        api=["FiNo"],
        name=["FiFarm"],
        operator=["CoName"],
        type_fields=["TblOpDesc"],
        status=["TblPsDesc"],
        date_fields=["FiStatDt"],
        lat=[],
        lon=[],
        source_updated="2026-09-22",
        coverage="live full status",
        extra_layers=[
            {
                "url": "https://energy.virginia.gov/gis/rest/services/DGO/DGO_wells/FeatureServer/5",
                "where": "1=1",
                "force_class": "plugged",
                "force_status": "Plugged",
            }
        ],
        mapping={
            "Active": ["Producing"],
            "Inactive": ["Shut In", "Partial Plug/Shut In"],
            "Other": ["Orphaned"],
        },
    ),
    _src(
        state="MT",
        agency="Montana Board of Oil and Gas Conservation (DNRC)",
        source_name="BOG DataMiner (layer 11)",
        source_url="https://gis.dnrc.mt.gov/arcgis/rest/services/BOG/DataMiner/FeatureServer/11",
        kind="arcgis",
        page_size=2000,
        where="Type IN ('Gas','Coal Bed Methane')",
        out_fields="API_WellNo,Well_Nm,CoName,Type,Status,Completed",
        api=["API_WellNo"],
        name=["Well_Nm"],
        operator=["CoName"],
        type_fields=["Type"],
        status=["Status"],
        date_fields=["Completed"],
        lat=[],
        lon=[],
        source_updated="UNKNOWN",
        coverage="live full status",
        mapping={
            "Active": ["Producing", "Domestic"],
            "Inactive": ["Shut In", "TA"],
            "Plugged": ["P&A - Approved"],
            "Other": ["Completed", "Abandoned - Unapproved"],
        },
    ),
    _src(
        state="AL",
        agency="State Oil and Gas Board of Alabama",
        source_name="OGB map (layer 3)",
        source_url="https://map.ogb.state.al.us/arcgis/rest/services/OGB/map/MapServer/3",
        kind="arcgis",
        page_size=2000,
        where="WEBOGBSDE.DBO.WebWell_Prj.WellType IN ('GAS','GC','CM','SHG')",
        out_fields="WEBOGBSDE.DBO.WebWell_Prj.API,WEBOGBSDE.DBO.WebWell_Prj.WellName,WEBOGBSDE.DBO.WebWell_Prj.Operator,WEBOGBSDE.DBO.WebWell_Prj.WellType,WEBOGBSDE.DBO.WebWell_Prj.StatusDesc,WEBOGBSDE.DBO.WebWell_Prj.PermitDate,WEBOGBSDE.DBO.WebWell_Prj.Latitude,WEBOGBSDE.DBO.WebWell_Prj.Longitude",
        api=["WEBOGBSDE.DBO.WebWell_Prj.API", "API"],
        name=["WEBOGBSDE.DBO.WebWell_Prj.WellName", "WellName"],
        operator=["WEBOGBSDE.DBO.WebWell_Prj.Operator", "Operator"],
        type_fields=["WEBOGBSDE.DBO.WebWell_Prj.WellType", "WellType"],
        status=["WEBOGBSDE.DBO.WebWell_Prj.StatusDesc", "StatusDesc"],
        date_fields=["WEBOGBSDE.DBO.WebWell_Prj.PermitDate", "PermitDate"],
        lat=["WEBOGBSDE.DBO.WebWell_Prj.Latitude", "Latitude"],
        lon=["WEBOGBSDE.DBO.WebWell_Prj.Longitude", "Longitude"],
        source_updated="2025-11-24",
        coverage="live full status",
        mapping={
            "Active": ["Producing", "Active"],
            "Inactive": ["Temporarily Abandoned"],
            "Plugged": ["Plugged and Abandoned", "Dry and Abandoned"],
            "Other": ["Released Jurisdiction", "Plugged Back", "Converted", "Permitted Well"],
        },
    ),
    _src(
        state="ND",
        agency="ND Dept of Mineral Resources, Oil and Gas Division",
        source_name="DMR public Wells (layer 0)",
        source_url="https://gis.dmr.nd.gov/dmrpublicservices/rest/services/Wells/FeatureServer/0",
        kind="arcgis",
        page_size=2000,
        where="well_type IN ('GASD','GASC','GASN','CBM','OG')",
        out_fields="api_no,well_name,operator,well_type,status,spud_date,latitude,longitude",
        api=["api_no"],
        name=["well_name"],
        operator=["operator"],
        type_fields=["well_type"],
        status=["status"],
        date_fields=["spud_date"],
        lat=["latitude"],
        lon=["longitude"],
        source_updated="2026-09-16",
        coverage="live full status",
        note="OG wells are oil and gas combined. The source does not separate associated gas.",
        mapping={
            "Active": ["A"],
            "Inactive": ["IA", "TA"],
            "Plugged": ["PA"],
            "Other": ["DRY", "PNC", "AB"],
        },
    ),
    _src(
        state="KS",
        agency="Kansas Geological Survey (KGS)",
        source_name="oilgas_wells (layer 0)",
        source_url="https://services.kgs.ku.edu/arcgis8/rest/services/oilgas/oilgas_wells/MapServer/0",
        kind="arcgis",
        page_size=1000,
        where="STATUS IN ('GAS','GAS-P&A','CBM','CBM-P&A','O&G','O&G-P&A')",
        out_fields="API_NUMBER,LEASE_NAME,WELL_NAME,OPERATOR_NAME,STATUS,PLUG_DATE,COMPLETION_DATE,NAD27_LATITUDE,NAD27_LONGITUDE",
        api=["API_NUMBER"],
        name=["LEASE_NAME", "WELL_NAME"],
        operator=["OPERATOR_NAME", "CURR_OPERATOR"],
        type_fields=["STATUS"],
        status=["STATUS"],
        date_fields=["PLUG_DATE", "COMPLETION_DATE"],
        lat=["NAD27_LATITUDE"],
        lon=["NAD27_LONGITUDE"],
        source_updated="UNKNOWN",
        coverage="partial status",
        note="KGS does not distinguish active from idle. Unplugged gas symbols are classed active.",
        mapping={
            "Active_or_unknown": ["GAS", "CBM", "O&G"],
            "Plugged": ["GAS-P&A", "CBM-P&A", "O&G-P&A"],
        },
    ),
    _src(
        state="WY",
        agency="Wyoming State Geological Survey (WOGCC data)",
        source_name="OilGas Data_layers (layer 12, January 3, 2025 well download)",
        source_url="https://portal.wsgs.wyo.gov/ags/rest/services/OilGas/Data_layers/MapServer/12",
        kind="arcgis",
        page_size=1000,
        where="WELL_CLASS='G'",
        out_fields="APINO,WN,COMPANY,WELL_CLASS,STATUS,STATUSDATE,LAT,LON",
        api=["APINO"],
        name=["WN"],
        operator=["COMPANY"],
        type_fields=["WELL_CLASS"],
        status=["STATUS"],
        date_fields=["STATUSDATE"],
        lat=["LAT"],
        lon=["LON"],
        source_updated="2025-01-03",
        coverage="file snapshot",
        mapping={
            "Active": ["PG"],
            "Inactive": ["SI", "TA"],
            "Plugged": ["PA"],
            "Other": ["EP", "SR", "NI", "NO", "PO"],
        },
    ),
    _src(
        state="CA",
        agency="CA Geologic Energy Management Division (CalGEM)",
        source_name="WellSTAR Wells (layer 0)",
        source_url="https://gis.conservation.ca.gov/server/rest/services/WellSTAR/Wells/MapServer/0",
        kind="arcgis",
        page_size=2000,
        where="WellType IN ('DG','GAS')",
        out_fields="API,LeaseName,WellNumber,OperatorName,WellType,WellStatus,SpudDate,Latitude,Longitude",
        api=["API"],
        name=["LeaseName", "WellNumber"],
        operator=["OperatorName"],
        type_fields=["WellType"],
        status=["WellStatus"],
        date_fields=["SpudDate"],
        lat=["Latitude"],
        lon=["Longitude"],
        source_updated="UNKNOWN",
        coverage="live full status",
        mapping={
            "Active": ["Active"],
            "Inactive": ["Idle"],
            "Plugged": ["Plugged"],
            "Other": ["Canceled"],
        },
    ),
    _src(
        state="MS",
        agency="MS Oil and Gas Board data, hosted by MARIS (university)",
        source_name="MS_Oil_n_Gas_Board_Wells_July_2025 (layer 0)",
        source_url="https://gis.mississippi.edu/server/rest/services/UtilityTelecom/MS_Oil_n_Gas_Board_Wells_July_2025/MapServer/0",
        kind="arcgis",
        page_size=2000,
        where="type='GAS'",
        out_fields="API,DispName,type,status,statdesc",
        api=["API"],
        name=["DispName"],
        operator=[],
        type_fields=["type"],
        status=["status", "statdesc"],
        date_fields=[],
        lat=[],
        lon=[],
        source_updated="2025-07",
        coverage="file snapshot",
        mapping={
            "Active": ["PR"],
            "Inactive": ["CI/TA", "CI", "TA"],
            "Plugged": ["PA"],
        },
    ),
    _src(
        state="KY",
        agency="Kentucky Geological Survey (KGS)",
        source_name="KYOilGasWells_static_WGS84 (layer 1)",
        source_url="https://kgs.uky.edu/arcgis/rest/services/KYOilGas/KYOilGasWells_static_WGS84/MapServer/1",
        kind="arcgis",
        page_size=2000,
        where="original_result='GAS'",
        out_fields="API_Number,farm_name,operator,original_result,plugged,date_plugged,date_modified,north_latitude83,west_longitude83",
        api=["API_Number"],
        name=["farm_name"],
        operator=["operator"],
        type_fields=["original_result"],
        status=["plugged"],
        date_fields=["date_plugged", "date_modified"],
        lat=["north_latitude83"],
        lon=["west_longitude83"],
        source_updated="2026-09-21",
        coverage="partial status",
        note="Completion result plus a plugged flag. Active versus idle is UNKNOWN.",
        plugged_flag=True,
        mapping={},
    ),
    _src(
        state="IL",
        agency="Illinois State Geological Survey",
        source_name="ILOIL Wells (layer 8)",
        source_url="https://maps.isgs.illinois.edu/arcgis/rest/services/ILOIL/Wells/MapServer/8",
        kind="arcgis",
        page_size=2000,
        where="STATUS_TEXT LIKE '%Gas Producer%' OR STATUS_TEXT LIKE '%Methane%'",
        out_fields="API_NUMBER,FARM_NAME,COMPANY_NAME,STATUS_TEXT,PERMIT_DATE,LATITUDE,LONGITUDE",
        api=["API_NUMBER"],
        name=["FARM_NAME"],
        operator=["COMPANY_NAME"],
        type_fields=["STATUS_TEXT"],
        status=["STATUS_TEXT"],
        date_fields=["PERMIT_DATE"],
        lat=["LATITUDE"],
        lon=["LONGITUDE"],
        source_updated="2026-08-28",
        coverage="partial status",
        note="Status text marks plugged wells. Active versus idle is UNKNOWN.",
        mapping={
            "Active_or_unknown": ["Gas Producer", "Combination Oil and Gas Producer", "Coal Bed Methane"],
            "Plugged": ["Gas Producer, Plugged", "Combination Oil and Gas Producer, Plugged"],
        },
    ),
    _src(
        state="TN",
        agency="TN Dept of Environment and Conservation, Oil and Gas",
        source_name="Oil_and_Gas2 Oil and Gas Wells (layer 0)",
        source_url="https://tdeconline.tn.gov/arcgis/rest/services/Oil_and_Gas2/MapServer/0",
        kind="arcgis",
        page_size=2000,
        where="PURPOSE_OF_WELL IN ('Gas','Shut-in Gas','NCG - Domestic','Oil And Gas')",
        out_fields="API_NO,WELL_NAME_AND_NO,OPERATOR_NAME,PURPOSE_OF_WELL,PERMIT_DATE,LATITUDE,LONGITUDE",
        api=["API_NO"],
        name=["WELL_NAME_AND_NO"],
        operator=["OPERATOR_NAME"],
        type_fields=["PURPOSE_OF_WELL"],
        status=["PURPOSE_OF_WELL"],
        date_fields=["PERMIT_DATE"],
        lat=["LATITUDE"],
        lon=["LONGITUDE"],
        source_updated="2026-08-06",
        coverage="partial status",
        note="Only Shut-in Gas carries an idle status. Other gas symbols are not split into producing versus idle.",
        mapping={
            "Active_or_unknown": ["Gas", "NCG - Domestic", "Oil And Gas"],
            "Inactive": ["Shut-in Gas"],
        },
    ),
    _src(
        state="AK",
        agency="Alaska Oil and Gas Conservation Commission",
        source_name="AOGCC_SQL_Test MapServer (layer 5)",
        source_url="https://maps.commerce.alaska.gov/server/rest/services/AOGCC/AOGCC_SQL_Test/MapServer/5",
        kind="arcgis",
        page_size=2000,
        where="WellStatus LIKE '%GAS%'",
        out_fields="API,WellName,WellStatus,Latitude,Longitude",
        api=["API"],
        name=["WellName"],
        operator=[],
        type_fields=["WellStatus"],
        status=["WellStatus"],
        date_fields=[],
        lat=["Latitude"],
        lon=["Longitude"],
        source_updated="UNKNOWN",
        coverage="partial status",
        note="Gas is identifiable while the well is active. Idle and plugged gas counts are UNKNOWN.",
        mapping={"Active": ["1-GAS", "2-GAS", "3-GAS"]},
    ),
    _src(
        state="SD",
        agency="SD DANR / SD Geological Survey (hosted by USD)",
        source_name="SDGS Interactive Data Map (layer 26)",
        source_url="https://gis.usd.edu/arcgis/rest/services/SDGS_Interactive_Data_Map/MapServer/26",
        kind="arcgis",
        page_size=2000,
        where="Well_Type_Current='Gas'",
        out_fields="API_Number,Well_Name,Operator,Well_Type_Current,Well_AdminStatus,Date_plug,EXPORT_DATE,lat,long",
        api=["API_Number"],
        name=["Well_Name"],
        operator=["Operator"],
        type_fields=["Well_Type_Current"],
        status=["Well_AdminStatus"],
        date_fields=["Date_plug", "EXPORT_DATE"],
        lat=["lat"],
        lon=["long"],
        source_updated="2026-09-11",
        coverage="live full status",
        mapping={
            "Active": ["Producing"],
            "Inactive": ["Shut In", "Temporarily Abandoned"],
            "Plugged": ["Plugged and Abandoned"],
            "Other": ["Converted-Domestic Gas", "Converted-Fresh Water Supply"],
        },
    ),
    _src(
        state="NE",
        agency="Nebraska Oil and Gas Conservation Commission",
        source_name="NE_WELLS.zip daily shapefile",
        source_url="http://nogcc.ne.gov/Publications/NE_WELLS.zip",
        kind="shapefile",
        where_field="Well_Type",
        where_values=["Natural Gas Well"],
        api=["API_WellNo"],
        name=["Well_Name"],
        operator=["Co_Name"],
        type_fields=["Well_Type"],
        status=["Well_Statu"],
        date_fields=[],
        lat=["Lat"],
        lon=["Long"],
        source_updated="2026-09-24",
        coverage="file snapshot",
        mapping={
            "Active": ["PR"],
            "Inactive": ["SI", "TA"],
            "Plugged": ["PA"],
            "Other": ["AX", "AB", "PW"],
        },
    ),
]


def sources_for(states):
    wanted = {item.upper() for item in states} if states else None
    rows = []
    for src in SOURCES:
        if wanted and src["state"] not in wanted:
            continue
        rows.append(src)
    return rows
